### ISSUE TITLE
first version of Gemini use

### ISSUE THREAD

**Issue by mirceagavrizi** [swent-t16/Voyageur#183]
For a first usecase of the AI assistant, we would like to have the option to create a trip automatically based on some fixed input (location, duration, interests)

**Comment by ioanajianu** [comment]
Since trip info depends a lot on the user (users already decide on location, dates etc. by themselves), let's use the assistant to instead recommend some activities based on the trip info. 
A first prompt would be to recommend just the title of the activities and add them as drafts
